n=input('Digite algo:')
print('O tipo primitivo desse valor é ',type(n))
print('Só tem espacos?',(n.isspace()))
print('é um numero?', (n.isnumeric()))
print('é um alfabetico?', (n.isalpha()))
print('é alfanumerico?', (n.isalnum()))
print('Está em maiúsculas?', (n.islower()))
print('Está em minúsculo?', (n.isupper()))
print('Está capitalizado?',(n.istitle) )