nome = str(input('Digite seu nome completo:')).strip()
print('Analisando seu nome...')
maius = nome.upper()
menus = nome.lower()
letras = len(nome) -nome.count(' ')
dividido = nome.split()
separa = len(dividido[0])
print(f'Seu nome em  maiúsculas é {nome}')
print(f'Seu nome em menusculas é {menus}')
print(f'Seu nome tem ao todo letras {letras}')
print(f'Seu primeiro nome é {dividido[0]} e tem  letras {separa}')
