times = ('Athletico Paranaense','Atlético-MG','Bahia','Botafogo','Chapecoense','Corinthians','Coritiba','Cruzeiro','Flamengo','Fluminense')
print('-='*90)
print(f'Lista de times {times}')
print('-='*90)
print(f'Osa 5 primeiros sao:{times[:5]}')
print('-='*90)
print(f'Os 4 ultimos sao {times[-4:]}')
print('-='*90)
print(f'Times em ordem alfabetica {sorted(times)}')
print('-='*90)
print(f'O chapecoense está na {times.index('Chapecoense')+1} posicao')